# Generated by Django 5.1.2 on 2024-11-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_filepdf_institution_policy_specialization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
