# Generated by Django 5.1.2 on 2024-11-01 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_user_middle_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="doctors",
            options={"verbose_name": "Доктор", "verbose_name_plural": "Докторы"},
        ),
        migrations.AlterModelOptions(
            name="researchresults",
            options={
                "verbose_name": "Результаты исследования",
                "verbose_name_plural": "Результаты исследований",
            },
        ),
        migrations.AlterModelOptions(
            name="specialization",
            options={
                "verbose_name": "Специализация",
                "verbose_name_plural": "Специализации",
            },
        ),
        migrations.AddField(
            model_name="researchresults",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="researchresults",
            name="date",
            field=models.DateField(auto_now=True, verbose_name="Дата исследования"),
        ),
        migrations.AlterField(
            model_name="researchresults",
            name="file_path",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="app.filepdf",
                verbose_name="Путь к файлу",
            ),
        ),
        migrations.AlterField(
            model_name="researchresults",
            name="institution",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.institution",
                verbose_name="Название института",
            ),
        ),
        migrations.AlterField(
            model_name="researchresults",
            name="name_research",
            field=models.CharField(
                max_length=100, verbose_name="Название исследования"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="middle_name",
            field=models.CharField(default="", max_length=30, verbose_name="Отчество"),
        ),
    ]
