# Generated by Django 5.1.2 on 2024-11-01 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_records_date_record'),
    ]

    operations = [
        migrations.RenameField(
            model_name='records',
            old_name='date',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='records',
            old_name='date_record',
            new_name='record_date',
        ),
    ]
