# Generated by Django 5.1.2 on 2024-11-01 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_date_records_create_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='records',
            old_name='create_date',
            new_name='date_create',
        ),
        migrations.RenameField(
            model_name='records',
            old_name='record_date',
            new_name='date_record',
        ),
    ]
