# Generated by Django 5.1.2 on 2024-11-01 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_records_name_records'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='name_records',
            field=models.CharField(default='', max_length=100),
        ),
    ]
