# Generated by Django 5.1.2 on 2024-11-02 15:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_records_name_records"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="direction",
            options={
                "verbose_name": "Направление",
                "verbose_name_plural": "Направления",
            },
        ),
        migrations.AlterModelOptions(
            name="doctorsreviews",
            options={
                "verbose_name": "Отзыв на врача",
                "verbose_name_plural": "Отзывы на врачей",
            },
        ),
        migrations.AlterModelOptions(
            name="filepdf",
            options={"verbose_name": "Файл PDF", "verbose_name_plural": "Файлы PDF"},
        ),
        migrations.AlterModelOptions(
            name="institution",
            options={"verbose_name": "Институт", "verbose_name_plural": "Институты"},
        ),
        migrations.AlterModelOptions(
            name="records",
            options={"verbose_name": "Запись", "verbose_name_plural": "Записи"},
        ),
        migrations.AddField(
            model_name="institution",
            name="address",
            field=models.CharField(default=None, max_length=255, verbose_name="Адрес"),
        ),
        migrations.AlterField(
            model_name="direction",
            name="institution",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.institution",
                verbose_name="Название учреждения",
            ),
        ),
        migrations.AlterField(
            model_name="direction",
            name="name_direction",
            field=models.CharField(max_length=255, verbose_name="Название направления"),
        ),
        migrations.AlterField(
            model_name="direction",
            name="until_time",
            field=models.DateField(verbose_name="дата посещения"),
        ),
        migrations.AlterField(
            model_name="direction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="doctorsreviews",
            name="date",
            field=models.DateField(auto_now=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="doctorsreviews",
            name="description",
            field=models.TextField(default=None, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="doctorsreviews",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app.doctors",
                verbose_name="Доктор",
            ),
        ),
        migrations.AlterField(
            model_name="doctorsreviews",
            name="raiting",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Рейтинг",
            ),
        ),
        migrations.AlterField(
            model_name="doctorsreviews",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="filepdf",
            name="file_path",
            field=models.FileField(upload_to="", verbose_name="Путь к файлу"),
        ),
        migrations.AlterField(
            model_name="filepdf",
            name="name_file",
            field=models.CharField(max_length=255, verbose_name="Название файла"),
        ),
        migrations.AlterField(
            model_name="institution",
            name="description",
            field=models.TextField(verbose_name="Описание института"),
        ),
        migrations.AlterField(
            model_name="institution",
            name="name_institution",
            field=models.CharField(max_length=255, verbose_name="Название института"),
        ),
        migrations.AlterField(
            model_name="user",
            name="policy",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.policy",
                verbose_name="Полис",
            ),
        ),
    ]
