# Generated by Django 5.1.3 on 2024-11-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0021_alter_specialization_specialization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specialization",
            name="specialization",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Специализация"
            ),
        ),
    ]
