# Generated by Django 5.1.3 on 2024-11-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_filepdf_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Отчество'),
        ),
    ]
