# Generated by Django 5.1.3 on 2024-11-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0027_alter_filepdf_file_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="records",
            name="date_record",
            field=models.DateField(auto_now_add=True, verbose_name="День записи"),
        ),
        migrations.AlterField(
            model_name="user",
            name="middle_name",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=30,
                null=True,
                verbose_name="Отчество",
            ),
        ),
    ]
