# Generated by Django 5.1.3 on 2024-11-15 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_records_user'),
        ('app', '0028_alter_user_middle_name'),
    ]

    operations = [
    ]
