# Generated by Django 5.1.3 on 2024-11-15 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_merge_0002_records_user_0028_alter_user_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='date_record',
            field=models.DateField(auto_now_add=True, verbose_name='День записи'),
        ),
        migrations.AlterField(
            model_name='records',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
